name: Feature Request
description: Suggest an idea for this project
title: "Feature: <title>"
labels: ["enhancement"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: basic-example
    attributes:
      label: Basic Example
      description: >-
        If applicable, provide a basic example or pseudo-code demonstrating the feature.
      render: python

  - type: textarea
    id: drawbacks
    attributes:
      label: Drawbacks and Impact
      description: >-
        What are the potential drawbacks or negative impacts of this feature?

  - type: textarea
    id: unresolved-questions
    attributes:
      label: Unresolved Questions
      description: >-
        What parts of the design are still to be determined?
